### ISSUE TITLE
Add compose version support

### ISSUE THREAD

**Issue by clarkshu1016** [gary-archer/oauth.mobilesample.android#24]
Would you think about adding compose version support in the future?

**Comment by gary-archer** [comment]
That's a good request. Jetpack Compose has come onto my radar recently, and seems to be the default application type in the latest Android Studio.

At first sight it looks much nicer than the ugly XML based views that have been required in Android for a long time. It will also make the app's code a lot more equivalent to my iOS, web and desktop samples. That is good since the same patterns across technologies is something I'm trying to demonstrate.

So I will look to make such an update in the coming months, when I get some time. The way the code is structured, hopefully only view code will need to change.

**Comment by gary-archer** [comment]
I updated the UI to compose - it is quite a bit simpler now than the older XML views
