### ISSUE TITLE
App is out of date?

### ISSUE THREAD

**Issue by pvandwalle** [gary-archer/oauth.mobilesample.android#35]
Tried the app yesterday on MacOS:

Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 10, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11609105 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
Kotlin Plugin: K2 Kotlin Mode (Alpha)
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true

On emulator:
Pixel_3a_API_34_extension_level_7_arm64-v8a

The App compiles and run which is great in itself, but seem there are maybe a few problems? For instance the Sign-in button doesn't do anything for me. There's nothing in logcat coming out.

Just putting this here in case there is interest in trying to debug. 

Best,
Pierre

**Comment by gary-archer** [comment]
Hi Pierre,

- If your emulator does not have Play Store / Google Chrome installed, that would explain the problem, since the code sample uses a Chrome Custom Tab.
- Also ensure that you configure a PIN on the emulator before clicking Sign In, since the app is meant to do nothing if Sign In is clicked when a PIN is not configured.

I ran the app OK this morning on may macOS 14.5 system. I run an x64 architecture, though that shouldn't change anything.

![Screenshot 2024-07-12 at 09 18 05](https://github.com/user-attachments/assets/42968696-07ab-42b1-9e97-594adb5a926e)

![Screenshot 2024-07-12 at 09 21 34](https://github.com/user-attachments/assets/83c7b2ef-c3f0-4651-aa3d-e570ee6d01be)

If you need to debug, [this code is hit](https://github.com/gary-archer/oauth.mobilesample.android/blob/master/app/src/main/java/com/authsamples/basicmobileapp/app/MainActivity.kt#L290) when you click Sign In, so you could output statements to logcat or set breakpoints there. Hope this gets you up and running. Always interested in ideas for improvements to code and docs ...

Regards,

Gary
